name: Auth service CD pipeline

on:
  push:
    branches: [ "master" ]
    paths:
      - "auth-service/**"
      - "kafka/**"
      - "gradle/**"
      - "*.gradle"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'

      - name: Build and run tests
        run: ./gradlew :auth-service:build

      - name: Store reports
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: reports
          path: |
            auth-service/build/reports/
            auth-service/build/test-results/