name: Gateway CD pipeline

on:
  push:
    branches: [ "master" ]
    paths:
      - "gateway/**"
      - "gradle/**"
      - "*.gradle"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'

      - name: Build and run tests
        run: ./gradlew :gateway:build

      - name: Store reports
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: reports
          path: |
            gateway/build/reports/
            gateway/build/test-results/