name: Task service CD pipeline

on:
  push:
    branches: [ "master" ]
    paths:
      - "task-service/**"
      - "kafka/**"
      - "gradle/**"
      - "*.gradle"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build and run tests
        run: ./gradlew :task-service:build

      - name: Store reports
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: reports
          path: |
            task-service/build/reports/
            task-service/build/test-results/